### ISSUE TITLE
Trying to resolve locales modules

### ISSUE THREAD

**Issue by Vincz** [halt-hammerzeit/webpack-react-redux-isomorphic-render-example#10]
Hi! First thanks for the hard work on universal app with react. 
I'm currently trying to move from react-isomorphic-tools to universal-webpack.
In my webpack config, i added a modulesDirectories config with the client folder (code/client). 
`modulesDirectories: ['code/client', 'node_modules']`

I expected to be able to require my module directly by doing something like:

`import MyComponent from "components/MyComponent"`

instead of (depending of the requiring file):

`import MyComponent from "../../components/MyComponent"`

It doest build for the client, but not for the page-server, throwing an error like: 

`Error: Cannot find module 'components'`

I don't know how to resolve this issue. 

Many thanks :)

**Comment by catamphetamine** [comment]
Try using `resolve.alias` instead
https://github.com/halt-hammerzeit/universal-webpack/blob/master/source/server%20configuration.js#L154-L166

``` js
    resolve: {
        alias: {
            'components': path.resolve(__dirname, '../code/client/components')
        }
    }
```

That should work

**Comment by Vincz** [comment]
It works! Many thanks :)

**Comment by savovs** [comment]
Hi guys, I'm having this resolve issue despite having aliases set up, I can't figure out what's wrong. Can you give [this](https://github.com/savovs/yupty-front/tree/universal-webpack) a look?
