### ISSUE TITLE
Would React-hot-loader 3.0 be easy to upgrade to?

### ISSUE THREAD

**Issue by adailey14** [halt-hammerzeit/webpack-react-redux-isomorphic-render-example#14]
Hey Halt-hammerzeit,

Have you tried out react-hot-loader 3.0 yet? (I have not). Gaearon says it fixes a lot of the issues in the previous hot reloading libraries he had put together. It's still in a beta phase.

A few references:
https://github.com/gaearon/react-hot-loader/pull/240
https://github.com/gaearon/react-hot-boilerplate/pull/61

I may experiment with it myself if I have time, but I bet you would have a better idea how to do it. I honestly don't really understand how any of the hot reloading stuff works or is configured.

**Comment by adailey14** [comment]
I've been reading about react-hot-loader 3.0 since posting this. I think it's not quite ready yet. Also I saw you made some comments in that project so you're aware of it. I will close this!

**Comment by catamphetamine** [comment]
Yeah, I tried to switch to the new loader the first day it was announced but obviously that was too optimistic and the new loader had lots of issues from the start.
I then realised that it needs a lot of debugging before it becomes usable in my use case (server-side rendering, etc).
It's still in beta.
When it's finally released I guess I'll go and switch to it.

**Comment by ignatevdev** [comment]
I was able to implement the beta 6 in my project and can provide the config if needed. Works fine for me

**Comment by catamphetamine** [comment]
@NSLS 
You're welcome.
Fork the repo and create a Pull Request.
Before submitting verify that:
- React components hot reload
- Redux reducers hot reload
- Redux actions aren't hot reloaded currently, but if they do that would be an extra plus

**Comment by catamphetamine** [comment]
@NSLS Or, if you're busy with other things, you could just provide a config and someone else could implement it in a Pull Request

**Comment by ignatevdev** [comment]
I've pulled the repo, but after looking at the config and realising that I don't remember anything from what I've done to move it to the react hot loader 3, since I took this project as a base and made too many changes and I don't have the time to think it all up again. So I'm going to publish my own boilerplate with all the changes I've got and obviously the newest hot loader and then anyone can look at how it's done and how it can be implemented. 

I will leave a link to the repo here as soon as I will publish it.

**Comment by catamphetamine** [comment]
@NSLS fair enough

**Comment by ignatevdev** [comment]
@adailey14 
I've successfully composed myself and posted a boilerplate for anyone, who finds this repo to be somewhat complicated and confusing.
You can now see, how I've been able to implement react-hot-loader@3 [here](https://github.com/NSLS/universal-webpack-boilerplate)

**Comment by catamphetamine** [comment]
@NSLS Ну смотри, теперь на тебе ответственность за работоспособное состояние твоего бойлерплейта, ибо я включил его в документацию
https://github.com/halt-hammerzeit/universal-webpack/commit/1566e5945387a2e81ae1b11bdfa2e0122e5cbbc8

**Comment by ignatevdev** [comment]
@halt-hammerzeit Affirmative

**Comment by catamphetamine** [comment]
@adailey14  FYI, upgraded the example project to the latest `react-hot-loader`
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example
