### ISSUE TITLE
is it possible to activate breakpoints using the debugger statement?

### ISSUE THREAD

**Issue by pailhead** [halt-hammerzeit/webpack-react-redux-isomorphic-render-example#15]
i'm trying to get familiar with as much as i can, figured this might be useful. Had to change the source-map setting though to even get to see the source and correct line numbers. Setting breakpoints in a debugging tool works, but the debugger statement is dropped.

**Comment by catamphetamine** [comment]
I'm not using debuggers myself so the answer is "I don't know"
