### ISSUE TITLE
Inlining css in <style> tag for server rendered pages

### ISSUE THREAD

**Issue by animeshchat** [halt-hammerzeit/webpack-react-redux-isomorphic-render-example#16]
Is there a way to inline css into the <style> tag on the server side?

I played around with the config and setting css_bundle to false, gets javascript to load the <style> tag on the client end. How do I make this happen on the server itself?

**Comment by catamphetamine** [comment]
See the `html.head` parameter
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example/blob/master/code/page-server/web%20server.js#L56
It lets embedding anything into the <head/>
