### ISSUE TITLE
Page server doesn't find files

### ISSUE THREAD

**Issue by londonbarrett** [halt-hammerzeit/webpack-react-redux-isomorphic-render-example#18]
Hello,

Very nice stack, so complete, i am having some problems with the config, the page server at port 3002 is not finding the files, it throws 404 for all. Also i would like to ask for a little explanation if possible, I don't understand why there are two servers and how they work.

**Comment by catamphetamine** [comment]
Page server only serves pages, the other one is API server, and the third one is the Proxy serving statics and stuff.

**Comment by catamphetamine** [comment]
What are the exact details of the error you get.

**Comment by londonbarrett** [comment]
it just doesn't find the files

**Comment by catamphetamine** [comment]
Post your complete console log, post the URL that's not found.

**Comment by londonbarrett** [comment]
GET http://localhost:3002/assets/main-ba1a2a26ab2a6b92fa9d02672f5fcc7c.css 
(index):40 GET http://localhost:3002/assets/9059f094ddb49c2b0fa6a254a6ebf2ad.jpg 404 (Not Found)
(index):66 GET http://localhost:3002/assets/main.375571b62039f6d34c4e.js

**Comment by catamphetamine** [comment]
Why are you running it on 3002?

**Comment by catamphetamine** [comment]
That's the reason

**Comment by londonbarrett** [comment]
hmmm i see, so i shouldn't use 3002?

**Comment by catamphetamine** [comment]
What does the readme say?

**Comment by londonbarrett** [comment]
Sorry, it is kind of a complex setup. I am trying to understand how it works

**Comment by londonbarrett** [comment]
do you have a gitter channel?

**Comment by catamphetamine** [comment]
It's not about the set up details, it's about a user reading the readme before posting an issue and following the directions

**Comment by londonbarrett** [comment]
It will help if there is more info about the setup

**Comment by catamphetamine** [comment]
See if the updated readme Summary section works for you.
