### ISSUE TITLE
Uncaught Error: imports[1] for react-transform-catch-errors does not look like a React component.

### ISSUE THREAD

**Issue by grantnorwood** [halt-hammerzeit/webpack-react-redux-isomorphic-render-example#2]
When running `npm run dev` and loading the example project in my browser at http://localhost:3000/ I'm getting an error in my console: 

```
(index.js:67) Uncaught Error: imports[1] for react-transform-catch-errors does not look like a React component.
```

However, running `npm run production` indeed works normally without errors.  Could you please advise me how I can fix this?  The error is thrown from within `node_modules/react-transform-catch-errors` but I'm not doing a very good job following the call stack to find the root cause of the problem in the example app.

Thank you so much!

**Comment by catamphetamine** [comment]
`npm install redbox-react@1.2.6 --save-dev`

**Comment by grantnorwood** [comment]
Thank you for such a quick response  :)
