### ISSUE TITLE
Doesn't run webserver in Windows 10

### ISSUE THREAD

**Issue by benoneal** [halt-hammerzeit/webpack-react-redux-isomorphic-render-example#24]
I've confirmed on two separate Win10 machines now: the web server running at port 3000 never starts. This is the last output when running it: 

``` javascript
Webpage rendering service is listening at port 3002
Hash: b9d58501467e3f9c9804
Version: webpack 2.2.1
Time: 5616ms
                                    Asset     Size  Chunks                    Chunk Names
     9059f094ddb49c2b0fa6a254a6ebf2ad.jpg  40.2 kB          [emitted]
             main.b9d58501467e3f9c9804.js  3.46 MB       0  [emitted]  [big]  main
main-4d7696adb13def249944e727c3796f4b.css  28.2 kB       0  [emitted]         main
webpack built b9d58501467e3f9c9804 in 5616ms
```
After this there is no output. I've left it for up to 30 minutes, and nothing else happens. Obviously nothing is ever run on localhost:3000 either.

**Comment by benoneal** [comment]
So after some more testing, it works if I run all four services separately in separate console tabs (dev-server, api, rendering-service, and webserver). 

But any attempt to run webserver in conjunction with the others in the same console tab, results in a hang that never results.

**Comment by catamphetamine** [comment]
Is this `npm run dev`?

**Comment by catamphetamine** [comment]
Webserver is started before webpack finishes:

```
Web server is listening
Now go to http://localhost:3000
(node:46374) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Webpage rendering service is listening at port 3002
Hash: fba9933954a4263f2d77
Version: webpack 2.2.1
Time: 7124ms
                                    Asset     Size  Chunks                    Chunk Names
     9059f094ddb49c2b0fa6a254a6ebf2ad.jpg  40.2 kB          [emitted]         
             main.fba9933954a4263f2d77.js  3.46 MB       0  [emitted]  [big]  main
main-80de5de0f6b540adf5d6fcf3266c40a1.css  27.7 kB       0  [emitted]         main
webpack built fba9933954a4263f2d77 in 7124ms
```

**Comment by catamphetamine** [comment]
I suppose you just didn't scroll up enough

**Comment by benoneal** [comment]
No, I scrolled through it, but the issue isn't the logging. I couldn't access localhost:3000. TCPView showed all other services running on their configured ports, but 3000 never ran. This can be reproduced 100% of the time not only on my own machine, but also on a friend's machine. We spent two hours on our machines debugging this issue over skype. Both with fresh installs from this repo. 

`npm run dev` literally never runs webserver on windows 10. Running them all seperately works. Running the dev server, api, and rendering service together works. Running any combination that includes webserver in the same console does not work.

**Comment by catamphetamine** [comment]
Hmm, I see.
I guess I'll keep this one open then.
Since I'm not on windows you're on your own with this one.
Though there's at least one another man who managed to run this on windows successfully
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example/issues/21

**Comment by alexicum** [comment]
Yes, it works for me without problem

**Comment by catamphetamine** [comment]
Since no one else reported on this possible issue I'm closing this
