### ISSUE TITLE
Breaks with tree-shaking. 

### ISSUE THREAD

**Issue by benoneal** [halt-hammerzeit/webpack-react-redux-isomorphic-render-example#25]
Amending babelrc to `["es2015", { "modules": false }]` causes builds to fail immediately, complaining about `unexpected token import` in whatever file is the first to use it as it walks the chain. 

Tried swapping out all imports/exports in all webpack config files to no avail. It just pushes the complaint back further and further.

**Comment by catamphetamine** [comment]
It is already being tree-shaken
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example/blob/master/client/src/.babelrc
