### ISSUE TITLE
Built main.js is HUGE

### ISSUE THREAD

**Issue by benoneal** [halt-hammerzeit/webpack-react-redux-isomorphic-render-example#26]
I ran into my [issue with tree shaking](https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example/issues/25) when trying to trouble-shoot this problem in my app. But since that broke, I just cloned the repo from scratch, ran `yarn`, then ran `npm run dev`, and main.js is just as massive. It's 3.54mb un-gzipped, which translates to roughly 1mb gzipped delivered to the browser. This is, roughly, 10 times larger than I'd expect it to be given my work on other, far more complex server-side rendered react applications. The built server.js file is a mere 82.3kb in comparison. 

Can you please look into this problem? This sort of file size is so unacceptable that if a solution isn't found I'm going to have to migrate my entire app to another boilerplate.

**Comment by catamphetamine** [comment]
You can migrate your entire app to whatever boilerplate you want.

What kind of man looks at the bundle size built with `DEVELOPMENT` flag.

**Comment by benoneal** [comment]
You're right. How silly of me. main.js is a tiny 958kb when built for production. That's only a mere 10x larger than it should be. 

Like, your attitude is pretty great when dealing with people who are using things you've built and trying to give you feedback on issues they are having with it, so that you can make it better and more useful. 

If this repo were a shining beacon of Everything Done Right, and produced code that was at least acceptable to use in a production app, then I'd probably overlook the arrogance. But c'mon, do you really think it's warranted to insult people when you can't even build something that would load in less than 10 seconds without any actual application code to run?

**Comment by catamphetamine** [comment]
I don't think you're a too skilled of a programmer if you can't even manage such simple things, and after that you can't even debug it yourself, so I'm freeing you of the burden of using my architectural decisions and you can now go and migrate your whatever app to whatever you find out there on the internets.

**Comment by catamphetamine** [comment]
For anyone browsing this issue: I've added `webpack-visualizer` plugin to the repo and now the bundle contents can be examined after `npm run production` via viewing the `./client/build/bundle-stats.html` file.

For more info:
https://blog.etleap.com/2017/02/02/inspecting-your-webpack-bundle/
