### ISSUE TITLE
Slow?

### ISSUE THREAD

**Issue by javajaws** [halt-hammerzeit/webpack-react-redux-isomorphic-render-example#27]
I just pulled this repo down and was wondering if it's normal for the GET of the user list to take so long?  For me its taking about 1.5s which seems really long given the list is empty and in memory (no db).   Doing a PUT for a user takes a similar amount of time - which when combined with the get to refresh causes a wait of around 3s.

Is this normal?  And if so, where is the time being spent?

**Comment by catamphetamine** [comment]
There are artificial delays in the Redux actions to illustrate the GUI.
See https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example/blob/master/client/src/redux/users.js
