### ISSUE TITLE
window._locale always seems to be undefined

### ISSUE THREAD

**Issue by farfarsfar** [halt-hammerzeit/webpack-react-redux-isomorphic-render-example#3]
I can't seem to get the locale-detection to work. The html lang attribute is always empty, and window.locale is undefined. Not sure how to proceed. Where should the options for koa be set? Is it in common/web server or in the react-isomorphic-render directory in ./node_modules?

![skarmavbild 2016-06-27 kl 11 23 29](https://cloud.githubusercontent.com/assets/15237589/16375024/a46e07d6-3c59-11e6-874f-927671eadd53.png)

Thanks!

**Comment by catamphetamine** [comment]
To have localization you should define `localize` function in your `page-server/web server.js`
https://github.com/halt-hammerzeit/react-isomorphic-render/blob/62fc8c5c5d1b8aa753f469b65f52c3f05c670a69/source/page-server/render.js#L39

```
import webpage_server from 'react-isomorphic-render/page-server'

// starts webpage rendering server
webpage_server
({
  ...

  // (optional)
  // supports internationalization
  // localize: async (store, preferred_locale) => { locale, messages }
})
```

https://github.com/halt-hammerzeit/react-isomorphic-render

(if you aren't using `async` then it will be `localize: (store, preferred_locale) => Promise.resolve({ locale, messages })`)

**Comment by farfarsfar** [comment]
Thanks so much! 

Some of those options are not explicitly present in page-server/web server.js in the render-example, probably why I didn’t think of them. 

However, and this must be down to my own inexperience, when I add the localize option as you specify, locale and message are undefined and throw a ReferenceError.

Like I said, I probably missed something obvious, would be nice if you could give another quick hint though!

Fabian

**Comment by catamphetamine** [comment]
What is your `localize` option and what is the full output of the error

**Comment by farfarsfar** [comment]
The option:

....},

localize: async(store, preferred_locale) => { locale, messages }

})

The error:
ReferenceError: locale is not defined

bootstrap 03ac574e2fddea6c86ab:39 _callee$
/Users/Fabian/projekt/qvitoo/qvitoo.api/src/qvitoo.com/build/server/webpack:/webpack/bootstrap 03ac574e2fddea6c86ab
runtime.js:88 tryCatch
[qvitoo.com]/[babel-runtime]/regenerator/runtime.js
runtime.js:341 GeneratorFunctionPrototype.invoke [as _invoke]
[qvitoo.com]/[babel-runtime]/regenerator/runtime.js
runtime.js:121 GeneratorFunctionPrototype.prototype.(anonymous function) [as next]
[qvitoo.com]/[babel-runtime]/regenerator/runtime.js
asyncToGenerator.js:17 step
[qvitoo.com]/[babel-runtime]/helpers/asyncToGenerator.js
asyncToGenerator.js:35
[qvitoo.com]/[babel-runtime]/helpers/asyncToGenerator.js
asyncToGenerator.js:14
[qvitoo.com]/[babel-runtime]/helpers/asyncToGenerator.js
bootstrap 03ac574e2fddea6c86ab:39 localize
/Users/Fabian/projekt/qvitoo/qvitoo.api/src/qvitoo.com/build/server/webpack:/webpack/bootstrap 03ac574e2fddea6c86ab
render.js:41 Object.callee$0$0$
[qvitoo.com]/[react-isomorphic-render]/source/page-server/render.js
runtime.js:88 tryCatch
[qvitoo.com]/[babel-runtime]/regenerator/runtime.js
runtime.js:341 GeneratorFunctionPrototype.invoke [as _invoke]
[qvitoo.com]/[babel-runtime]/regenerator/runtime.js
runtime.js:121 GeneratorFunctionPrototype.prototype.(anonymous function) [as next]
[qvitoo.com]/[babel-runtime]/regenerator/runtime.js
runtime.js:161 invoke
[qvitoo.com]/[babel-runtime]/regenerator/runtime.js
From previous event

runtime.js:214 AsyncIterator.enqueue
[qvitoo.com]/[babel-runtime]/regenerator/runtime.js
runtime.js:121 AsyncIterator.prototype.(anonymous function) [as next]
[qvitoo.com]/[babel-runtime]/regenerator/runtime.js
runtime.js:233 Object.runtime.async
[qvitoo.com]/[babel-runtime]/regenerator/runtime.js
render.js:56 Object.callee$0$0 [as default]
[qvitoo.com]/[react-isomorphic-render]/source/page-server/render.js
web server.js:155 Object.rendering$
[qvitoo.com]/[react-isomorphic-render]/babel-transpiled-modules/page-server/web server.js
runtime.js:88 tryCatch
[qvitoo.com]/[babel-runtime]/regenerator/runtime.js
runtime.js:341 GeneratorFunctionPrototype.invoke [as _invoke]
[qvitoo.com]/[babel-runtime]/regenerator/runtime.js
runtime.js:121 GeneratorFunctionPrototype.prototype.(anonymous function) [as next]
[qvitoo.com]/[babel-runtime]/regenerator/runtime.js
index.js:65 onFulfilled
[qvitoo.com]/[co]/index.js
index.js:54
[qvitoo.com]/[co]/index.js
index.js:50 Object.co
[qvitoo.com]/[co]/index.js
index.js:118 Object.toPromise
[qvitoo.com]/[co]/index.js
index.js:99 next
[qvitoo.com]/[co]/index.js
index.js:69 onFulfilled
[qvitoo.com]/[co]/index.js
index.js:54
[qvitoo.com]/[co]/index.js
index.js:50 Object.co
[qvitoo.com]/[co]/index.js
index.js:30 Object.createPromise
[qvitoo.com]/[co]/index.js
application.js:132 Server.<anonymous>
[qvitoo.com]/[react-isomorphic-render]/node_modules/koa/lib/application.js
events.js:100 emitTwo
events.js

**Comment by catamphetamine** [comment]
```
The option:

....},

localize: async (store, preferred_locale) => { locale, messages }

})


The error:
ReferenceError: locale is not defined

```

Well, of course.

Try this:

```
localize: async (store, preferred_locale) => { preferred_locale, { 'test.test': 'Русский' } }
```

**Comment by farfarsfar** [comment]
The option:

....},

localize: async(store, preferred_locale) => { locale, messages }

})

The error:
ReferenceError: locale is not defined

Well, of course.

Try this:

localize: async(store, preferred_locale) => { preferred_locale, { 'test.test': 'Русский' } }

Ok, that seems obvious now that you mention it.. Now the error is:
TypeError: Cannot read property 'locale' of undefined

I suppose this means that the result object in  render.js is undefined, but I don’t quite understand why.

(I really appreciate you helping out by the way.
Don’t want to take up your time with simple debugging though, I’ll try bugging some of my JS knowledgeable colleagues in the future.)

render.js:43 Object.callee$0$0$
[qvitoo.com]/[react-isomorphic-render]/source/page-server/render.js
runtime.js:88 tryCatch
[qvitoo.com]/[babel-runtime]/regenerator/runtime.js
runtime.js:341 GeneratorFunctionPrototype.invoke [as _invoke]
[qvitoo.com]/[babel-runtime]/regenerator/runtime.js
runtime.js:121 GeneratorFunctionPrototype.prototype.(anonymous function) [as next]
[qvitoo.com]/[babel-runtime]/regenerator/runtime.js
runtime.js:161 GeneratorFunctionPrototype.invoke
[qvitoo.com]/[babel-runtime]/regenerator/runtime.js
timers.js:534 tryOnImmediate
timers.js
timers.js:514 processImmediate [as _immediateCallback]
timers.js
From previous event

runtime.js:163 invoke
[qvitoo.com]/[babel-runtime]/regenerator/runtime.js
runtime.js:195 callInvokeWithMethodAndArg
[qvitoo.com]/[babel-runtime]/regenerator/runtime.js
runtime.js:215 previousPromise
[qvitoo.com]/[babel-runtime]/regenerator/runtime.js
From previous event

runtime.js:214 AsyncIterator.enqueue
[qvitoo.com]/[babel-runtime]/regenerator/runtime.js
runtime.js:121 AsyncIterator.prototype.(anonymous function) [as next]
[qvitoo.com]/[babel-runtime]/regenerator/runtime.js
runtime.js:233 Object.runtime.async
[qvitoo.com]/[babel-runtime]/regenerator/runtime.js
render.js:56 Object.callee$0$0 [as default]
[qvitoo.com]/[react-isomorphic-render]/source/page-server/render.js
web server.js:155 Object.rendering$
[qvitoo.com]/[react-isomorphic-render]/babel-transpiled-modules/page-server/web server.js
runtime.js:88 tryCatch
[qvitoo.com]/[babel-runtime]/regenerator/runtime.js
runtime.js:341 GeneratorFunctionPrototype.invoke [as _invoke]
[qvitoo.com]/[babel-runtime]/regenerator/runtime.js
runtime.js:121 GeneratorFunctionPrototype.prototype.(anonymous function) [as next]
[qvitoo.com]/[babel-runtime]/regenerator/runtime.js
index.js:65 onFulfilled
[qvitoo.com]/[co]/index.js
index.js:54
[qvitoo.com]/[co]/index.js
index.js:50 Object.co
[qvitoo.com]/[co]/index.js
index.js:118 Object.toPromise
[qvitoo.com]/[co]/index.js
index.js:99 next
[qvitoo.com]/[co]/index.js
index.js:69 onFulfilled
[qvitoo.com]/[co]/index.js
index.js:54
[qvitoo.com]/[co]/index.js
index.js:50 Object.co
[qvitoo.com]/[co]/index.js
index.js:30 Object.createPromise
[qvitoo.com]/[co]/index.js
application.js:132 Server.<anonymous>
[qvitoo.com]/[react-isomorphic-render]/node_modules/koa/lib/application.js
events.js:100 emitTwo
events.js

**Comment by catamphetamine** [comment]
```

TypeError: Cannot read property 'locale' of undefined

I suppose this means that the result object in  render.js is undefined, but I don’t quite understand why.
```

Oh, ha ha, didn't notice that.
The correct function will be:

```

localize: async (store, preferred_locale) => { locale: preferred_locale, messages: { 'test.test': 'Русский' } }
```

**Comment by catamphetamine** [comment]
Actually, that one is not correct too.
Just write it multiline:

```
localize: async function(store, preferred_locale) {
    return {
        locale: preferred_locale,
        messages: { 'test.test': 'Русский' }
    }
}
```

This one works, I checked.

**Comment by farfarsfar** [comment]
Wonderful! 

Seems to be working, except for this error (with regards to the client side, i suppose).
Should I add the mentioned function in client/application.js? 

Unhandled rejection Error: You are supposed to pass 
                        "load_localized_messages(locale) => Promise" function 
                        as a parameter to client-side rendering function call
                        because you opted into using internationalization feature

```
at render (eval at <anonymous> (http://127.0.0.1:3001/assets/main.d07e4376a9ab5ffc2ef0.js:2402:2), <anonymous>:48:18)
at render_page (eval at <anonymous> (http://127.0.0.1:3001/assets/main.d07e4376a9ab5ffc2ef0.js:4424:2), <anonymous>:54:10)
at eval (eval at <anonymous> (http://127.0.0.1:3001/assets/main.d07e4376a9ab5ffc2ef0.js:1166:2), <anonymous>:37:19)
at Object.<anonymous> (http://127.0.0.1:3001/assets/main.d07e4376a9ab5ffc2ef0.js:1166:2)
at __webpack_require__ (http://127.0.0.1:3001/assets/main.d07e4376a9ab5ffc2ef0.js:583:30)
at fn (http://127.0.0.1:3001/assets/main.d07e4376a9ab5ffc2ef0.js:107:20)
at eval (eval at <anonymous> (http://127.0.0.1:3001/assets/main.d07e4376a9ab5ffc2ef0.js:728:2), <anonymous>:10:1)
at Object.<anonymous> (http://127.0.0.1:3001/assets/main.d07e4376a9ab5ffc2ef0.js:728:2)
at __webpack_require__ (http://127.0.0.1:3001/assets/main.d07e4376a9ab5ffc2ef0.js:583:30)
at fn (http://127.0.0.1:3001/assets/main.d07e4376a9ab5ffc2ef0.js:107:20)
at Object.<anonymous> (http://127.0.0.1:3001/assets/main.d07e4376a9ab5ffc2ef0.js:637:19)
at __webpack_require__ (http://127.0.0.1:3001/assets/main.d07e4376a9ab5ffc2ef0.js:583:30)
```

**Comment by catamphetamine** [comment]
`load_localized_messages(locale) => Promise`

Yes, you can write it like this (in `application.js`):

```
load_localized_messages(locale) => Promise.resolve({ 'test.test': 'Русский' })
```
