### ISSUE TITLE
Still getting a warning on the server about PropTypes

### ISSUE THREAD

**Issue by hifitodd** [halt-hammerzeit/webpack-react-redux-isomorphic-render-example#30]
Still getting a warning on the server: 

Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by catamphetamine** [comment]
Well, this message is obviously very non-descriptive and there's not much I can debug based on such a message.
They could have printed a stack trace at least using fake errors.
Until then, there's no way to guess.

**Comment by catamphetamine** [comment]
On a client side though it does give a stack trace which can be traced to `react-dnd`.
But the author seems to have abandoned his package because he's ignoring the issue.
https://github.com/react-dnd/react-dnd/issues/749
