### ISSUE TITLE
How to import scss files?

### ISSUE THREAD

**Issue by Iuriy-Budnikov** [halt-hammerzeit/webpack-react-redux-isomorphic-render-example#31]
Hey guys,
Thanks for your great work!

My example: `import styles from './Footer.scss';`
I added sass loader, but have following issue `You may need an appropriate loader to handle this file type.`

**Comment by catamphetamine** [comment]
So, did you resolve your issue

**Comment by Iuriy-Budnikov** [comment]
yeah, almost.
