### ISSUE TITLE
Make this example simpler by removing web-service

### ISSUE THREAD

**Issue by rolele** [halt-hammerzeit/webpack-react-redux-isomorphic-render-example#32]
Hi,
thanks for the good work, I am trying to figure it out how universal redux work but I find it disturbing that this example is actually using a lot of libraries.

The more disturbing one is "web-service", this is another library you developed and this make this example very complicated to me (trying to integrate universal-webpack in my app that does not use web-service)

**Comment by catamphetamine** [comment]
`web-service` is only used in the api service, it is not used neither in the rendering service nor on the client side

**Comment by rolele** [comment]
Ok thanks
