### ISSUE TITLE
css issue when importing material ui.

### ISSUE THREAD

**Issue by sunrise828** [halt-hammerzeit/webpack-react-redux-isomorphic-render-example#36]
Hello Nikolay!
I'm using your ssr sample with react material ui. so I designed all with material ui.
On dev mode, all is fine.
But when I run the project with production mode, then layouts and material ui componets style are messed.

How can I resolve it?
Best regards!

Material UI version is v1.0.0.

**Comment by catamphetamine** [comment]
> But when I run the project with production mode, then layouts and material ui componets style are messed.

Describe in more detail.

**Comment by sunrise828** [comment]
firstly I run following command for development.
`npm run dev`
in development mode, I could check all style is fine.
![screenshot_4](https://user-images.githubusercontent.com/37823468/40878025-40b80620-66bd-11e8-8ba0-4fc457c227a5.png)
Once I thought all done, I switched my project as production mode.
But some css styles and layouts are messed after loading page.
![screenshot_5](https://user-images.githubusercontent.com/37823468/40878068-1e591244-66be-11e8-992a-ec361a10e27f.png)

I checked necessary css files from material-ui are on head tag.

How can I resolve it.

**Comment by catamphetamine** [comment]
> But some css styles and layouts are messed after loading page.
> I checked necessary css files from material-ui are on head tag.

Then it means that either some styles are missing, or, most likely, that some styles are out-of-order.
`import` doesn't guarantee any order of styles.
`require()` does.

> How can I resolve it.

You can resolve it by inspecting styles through Chrome Dev Tools and seeing if all styles rules are included, if they're in the right order, or if they're missing.

**Comment by catamphetamine** [comment]
Also if you're using SASS then they recently released a version which also breaks `@import` order.
https://github.com/sass/node-sass/issues/2362#issuecomment-390451006
I'm not using SASS anymore, see the latest code.

**Comment by sunrise828** [comment]
And is it possible to disable SSR?
You mentioned SSR is optional on README.

**Comment by catamphetamine** [comment]
Yes, it's possible.
See this example which is without SSR:
https://github.com/catamphetamine/react-website-basic-example
It's for latest version of `react-website`

**Comment by catamphetamine** [comment]
Also there's `hollow: true/false` flag for disabling SSR page rendering:
https://github.com/catamphetamine/webpack-react-redux-server-side-render-example/blob/4629c6470daa343e7523df3995cd44012e4c6569/rendering-service/main.js#L77-L87
It only disables page rendering, i.e. the inside of the #react DOM element while the HTML page <head/> is still rendered on server side.
So it's not entirely "optional".
