### ISSUE TITLE
Does webpack serve pay attention to plugins?

### ISSUE THREAD

**Issue by tavurth** [halt-hammerzeit/webpack-react-redux-isomorphic-render-example#37]
In my `webpack.config.js` I have a plugin:

```js
// Ignore certain kinds of development scratch files
new webpack.WatchIgnorePlugin([/^\.#.*/]),
```

However, while `webpack --watch` does not rebuild when these files change, webpack-serve always rebuilds.

`webpack-serve` also seems to disregard `stats` part of the config, blobbing large amounts of text into the console when using `mini-css-extract-plugin` as part of a `universal-webpack` build system.

**Comment by catamphetamine** [comment]
Well, I guess you should report `webpack-serve`-specific bugs to their repo.
By the way, they usually don't want to fix their bugs, and there's no alternative to `webpack-serve` currently.

**Comment by tavurth** [comment]
Oops, sorry I thought I'd jumped to the `webpack-serve` repo, I'll report this there.

**Comment by tavurth** [comment]
https://github.com/webpack-contrib/webpack-serve/issues/169
