### ISSUE TITLE
Is it works in production mode?

### ISSUE THREAD

**Issue by 4u** [halt-hammerzeit/webpack-react-redux-isomorphic-render-example#38]
Hi! Can't get how it works in production. You have `webpack` in devDependencies, but `/rendering-service/index.js` requires `webpack.config`, which requires `webpack`. Do you use devDependency in production mode or I miss something in your implementation?

**Comment by catamphetamine** [comment]
Only `webpackConfig.output.path` is used internally so instead of importing the whole `webpack.config` one can just pass something like `{ output: { path: path.resolve(__dirname, '../dist') } }`.
I'm passing `webpack.config` there just for simplicity.
