### ISSUE TITLE
Can universal-webpack be used without react-website

### ISSUE THREAD

**Issue by narutosanjiv** [halt-hammerzeit/webpack-react-redux-isomorphic-render-example#39]
Right now, i am converting my react application from webpack-isomorphic-tools to univeral-webpack. But example here shown with react-website. Can this be used without  react-website?

**Comment by catamphetamine** [comment]
Indeed, this project is complex.
It can but, but there is no example without react-website.
You can create a minimal example for `univeral-webpack` without using any other libraries.
