### ISSUE TITLE
ReactDOM not defined when setting development_tools to true

### ISSUE THREAD

**Issue by farfarsfar** [halt-hammerzeit/webpack-react-redux-isomorphic-render-example#4]
I'm getting "ReactDOM is not defined" when I try to set the `development_tools` option to `true` in `application.js`.

Not sure how to solve this.

![skarmavbild 2016-07-04 kl 12 23 06](https://cloud.githubusercontent.com/assets/15237589/16557802/20893fce-41e2-11e6-9b81-14d3d63bb10e.png)

**Comment by catamphetamine** [comment]
Oh, really.
Try `react-isomorphic-render@3.0.3`

**Comment by catamphetamine** [comment]
I meant, do `npm install react-isomorphic-render@3.0.3`.
That should fix the issue.

**Comment by farfarsfar** [comment]
While that does fix the issue with `ReactDOM` being not defined, its `content_container` render destination also seems to be not defined.

**Comment by catamphetamine** [comment]
yeah, that's true, I'll fix that one

**Comment by catamphetamine** [comment]
I did some rewriting on the library and fixed DevTools.
Try `npm install react-isomorphic-render@3.0.5`

**Comment by catamphetamine** [comment]
In case you're interested I rewrote `react-isomorphic-render` to `4.0.0` and updated this project accordingly.

**Comment by farfarsfar** [comment]
Wow, you work fast.

I installed 3.0.4 today and that works well! Will check out 4.0 tomorrow.

Cheers,
Fabian

**Comment by farfarsfar** [comment]
Hello! 

I was just wondering if you have any success using dynamic routing within this example. The app I’m trying to migrate uses dynamic routing, like so:

``` js
export default {
  path: 'accounts',

  getChildRoutes(location, cb) {
    require.ensure([], (require) => {
      cb(null, [
        { path: 'activation',
          component: require('../pages/app/accounts/activation') },
        { path: 'details',
          component: require('../pages/app/accounts/details') },
        { path: 'forgot',
          component: require('../pages/app/accounts/forgot') },
        { path: 'login',
          component: require('../pages/app/accounts/login') },
        { path: 'logout',
          component: require('../pages/app/accounts/logout') },
        { path: 'password',
          component: require('../pages/app/accounts/password') },
        { path: 'reset',
          component: require('../pages/app/accounts/reset') },
        { path: 'signup',
          component: require('../pages/app/accounts/signup') },
        { path: 'verify',
          component: require('../pages/app/accounts/verify') }
      ]);
    });
  },

  getComponent(location, cb) {
    require.ensure([], (require) => {
      cb(null, require('../pages/app/accounts'))
    }, 'accounts')
  }
}
```

With components like this one, with child routes, I get a React markup warning and no render on client (apart from the <noscript> tag). I’ve found this pointer in the react-router guides:
https://github.com/reactjs/react-router/blob/master/docs/guides/ServerRendering.md#async-routes https://github.com/reactjs/react-router/blob/master/docs/guides/ServerRendering.md#async-routes

My question now is (I suppose): where would I add the code above? Or if you have made it some other way, how?

Kind regards,
Fabian

**Comment by catamphetamine** [comment]
This project uses `redux-router` for rendering both on client and server.
I can look into this issue if you fork this repo and convert it to one with "dynamic routing".
Then you post a link to the fork here, I check it out and see how it can be made working.

**Comment by farfarsfar** [comment]
Ok, I made a quick example, see what you make of this. The routes render fine on the server, but render empty on the client side.

https://github.com/farfarsfar/webpack-react-redux-isomorphic-render-example/commit/daefe648e8716ed4650008bb4e1edd2ab8f52b37 https://github.com/farfarsfar/webpack-react-redux-isomorphic-render-example/commit/daefe648e8716ed4650008bb4e1edd2ab8f52b37

Fabian

**Comment by catamphetamine** [comment]
I made the changes to make async routes work.
See the attached commit.

Checkout `async-routes` branch and do

```
npm install react-isomorphic-render@latest && npm run dev
```

There's a little `react-router` bug concerning menu links:
https://github.com/reactjs/react-router/issues/3675

I'll see into that later.

**Comment by catamphetamine** [comment]
Fixed the bug of the top menu links styleClasses

```
npm install react-isomorphic-render@latest && npm run dev
```

It is considered done and fully working now
