### ISSUE TITLE
require('babel-register') should ignore build/server.js

### ISSUE THREAD

**Issue by adailey14** [halt-hammerzeit/webpack-react-redux-isomorphic-render-example#5]
For my large project, I am making babel-register ignore the build folder in 'common/server entry.js' like this:

```
require('babel-register')({
  ignore: /.*(build|node_modules)\/.*/,
});
```

This speeds up the start time of my server a ton. Since you are already using webpack to babelify that code, I think you can ignore it in the babel-require. Does that make sense?

**Comment by catamphetamine** [comment]
Oh, good catch.

Yeah, I guess I should implement that too.

**Comment by catamphetamine** [comment]
@adailey14 @samarpanda
In the latest version I've incorporated this fix into the library itself.
See: https://github.com/halt-hammerzeit/universal-webpack#server-side-startup-time-optimization
