### ISSUE TITLE
Using webpack.babel.js and enforcing import

### ISSUE THREAD

**Issue by sidhuko** [halt-hammerzeit/webpack-react-redux-isomorphic-render-example#7]
Firstly, thanks for a great upgrade to your tools package! I appreciate what your old one was trying to do but it did feel a bit nasty to use but other workarounds seemed just as invasive so looking for alternatives when I found this package.

One of the biggest hurdle of this package is understanding how it is used it most practical applications. I've some suggestions to improve the implementation and examples. You should be able to support commonjs and es6 modules with webpack using webpack.babel.js format with babel-runtime and babel-loader installed will trigger the ES6 compiling. Its a not a well documented feature but very helpful. It would also be good to see a simple example **without** other builds tools like nodemon.  Including code for these development tools isn't nice for a such a great package. 

I'll link you to my fork once I've finished the changes I needed. If you could add an example within the repository without the other third-party dependencies it would really help me understand how you see this package being used at a simple level so I could help more in the future.

**Comment by catamphetamine** [comment]
> It would also be good to see a simple example without other builds tools like nodemon

You can create a repo, something like `universal-webpack-simplest-setup-example` where you would document everything as you would like it to see.
Then I would add a link to your project in the README (if it comes out a sufficiently good one)
The thing with simple demos is that in the real project users will use complex setups anyway (hot reloads, nodemons, bundling styles, etc).

> Including code for these development tools isn't nice for a such a great package.

Nodemon is not included in `universal-webpack`

> I'll link you to my fork once I've finished the changes I needed

I won't merge the changes, and I don't think I would link to a fork with the only change that nodemon isn't used.
It has to be a completely new-from-scratch and different code for me to include it as a link in the README.

> how you see this package being used at a simple level

Webpack is in no way simple, it's very advanced and complicated stuff. So are Redux, React-router, etc.
