### ISSUE TITLE
No styling in development mode

### ISSUE THREAD

**Issue by rosscourt** [halt-hammerzeit/webpack-react-redux-isomorphic-render-example#8]
When I access the app after running `npm run dev` no styling is loaded.

Styling does work when running as `npm run production`.

Am I missing something?

**Comment by catamphetamine** [comment]
What do you mean by "no styling is loaded"?

**Comment by rosscourt** [comment]
Turns out my corporate proxy was silently blocking the CSS file.

Didn't like the use of `127.0.0.1`, changing the `host` values in "configuration.defaults.js" to `localhost` solved this for me.
